.TH "liblbfgsb-examples" 1
.SH NAME
liblbfgsb-examples \- example programs using the L-BFGS-B library
.SH SYNOPSIS
.B lbfgsb-examples_*
.SH DESCRIPTION
The
.B lbfgsb-examples_*
programs are the compiled versions of the corresponding L-BFGS-B
library examples whose source files are installed in
/usr/share/doc/liblbfgsb-examples. The compiled programs do not in
themselves serve a purpose.
